### ISSUE TITLE
New Request FAILS

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#435]
Class ProcessMaker\Repositories\ExecutionInstanceRepository contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ProcessMaker\Nayra\Contracts\Repositories\ExecutionInstanceRepositoryInterface::createToken)

Doesn't pass PHPUnit tests. Cannot start a new request.

**Comment by velkymx** [comment]
``
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

.................F.............................................  63 / 235 ( 26%)
............................................................... 126 / 235 ( 53%)
............................................................... 189 / 235 ( 80%)
..........PHP Fatal error:  Class ProcessMaker\Repositories\ExecutionInstanceRepository contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ProcessMaker\Nayra\Contracts\Repositories\ExecutionInstanceRepositoryInterface::createToken) in /opt/processmaker/ProcessMaker/Repositories/ExecutionInstanceRepository.php on line 19
PHP Stack trace:
PHP   1. {main}() /opt/processmaker/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /opt/processmaker/vendor/phpunit/phpunit/phpunit:53
PHP   3. PHPUnit\TextUI\Command->run() /opt/processmaker/vendor/phpunit/phpunit/src/TextUI/Command.php:155
PHP   4. PHPUnit\TextUI\TestRunner->doRun() /opt/processmaker/vendor/phpunit/phpunit/src/TextUI/Command.php:200
PHP   5. PHPUnit\Framework\TestSuite->run() /opt/processmaker/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:566
PHP   6. PHPUnit\Framework\TestSuite->run() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestSuite.php:765
PHP   7. Tests\Feature\Api\Workflow\WorkflowTest->run() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestSuite.php:765
PHP   8. PHPUnit\Framework\TestResult->run() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestCase.php:798
PHP   9. Tests\Feature\Api\Workflow\WorkflowTest->runBare() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestResult.php:645
PHP  10. Tests\Feature\Api\Workflow\WorkflowTest->runTest() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestCase.php:844
PHP  11. Tests\Feature\Api\Workflow\WorkflowTest->testStartProcessAndCompleteTask() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestCase.php:1146
PHP  12. Tests\Feature\Api\Workflow\WorkflowTest->api() /opt/processmaker/tests/Feature/Api/Workflow/WorkflowTest.php:76
PHP  13. Tests\Feature\Api\Workflow\WorkflowTest->json() /opt/processmaker/tests/Feature/Api/ApiTestCase.php:44
PHP  14. Tests\Feature\Api\Workflow\WorkflowTest->call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:317
PHP  15. ProcessMaker\Http\Kernel->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:345
PHP  16. ProcessMaker\Http\Kernel->sendRequestThroughRouter() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
PHP  17. Illuminate\Routing\Pipeline->then() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
PHP  18. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
PHP  19. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  20. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  21. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
PHP  22. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  23. Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  24. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
PHP  25. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  26. Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  27. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
PHP  28. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  29. ProcessMaker\Http\Middleware\TrustProxies->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  30. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/fideloper/proxy/src/TrustProxies.php:57
PHP  31. ProcessMaker\Http\Kernel->Illuminate\Foundation\Http\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
PHP  32. Illuminate\Routing\Router->dispatch() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
PHP  33. Illuminate\Routing\Router->dispatchToRoute() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:597
PHP  34. Illuminate\Routing\Router->runRoute() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:608
PHP  35. Illuminate\Routing\Router->runRouteWithinStack() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:642
PHP  36. Illuminate\Routing\Pipeline->then() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:667
PHP  37. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
PHP  38. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  39. Illuminate\Auth\Middleware\Authenticate->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  40. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
PHP  41. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  42. Illuminate\Routing\Middleware\SubstituteBindings->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  43. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
PHP  44. Illuminate\Routing\Router->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
PHP  45. Illuminate\Routing\Route->run() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:665
PHP  46. Illuminate\Routing\Route->runController() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
PHP  47. Illuminate\Routing\ControllerDispatcher->dispatch() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
PHP  48. ProcessMaker\Http\Controllers\Api\Workflow\EventController->callAction() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
PHP  49. ProcessMaker\Http\Controllers\Api\Workflow\EventController->callAction() /opt/processmaker/ProcessMaker/Http/Controllers/Controller.php:35
PHP  50. call_user_func_array:{/opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
PHP  51. ProcessMaker\Http\Controllers\Api\Workflow\EventController->triggerStart() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
PHP  52. Illuminate\Support\Facades\Facade::triggerStartEvent() /opt/processmaker/ProcessMaker/Http/Controllers/Api/Workflow/EventController.php:23
PHP  53. Illuminate\Support\Facades\Facade::__callStatic() /opt/processmaker/ProcessMaker/Http/Controllers/Api/Workflow/EventController.php:23
PHP  54. ProcessMaker\Managers\WorkflowManager->triggerStartEvent() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223
PHP  55. ProcessMaker\Jobs\BpmnAction::dispatchNow() /opt/processmaker/ProcessMaker/Managers/WorkflowManager.php:35
PHP  56. Illuminate\Bus\Dispatcher->dispatchNow() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php:26
PHP  57. Illuminate\Pipeline\Pipeline->then() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98
PHP  58. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
PHP  59. Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116
PHP  60. ProcessMaker\Application->call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94
PHP  61. Illuminate\Container\BoundMethod::call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php:564
PHP  62. Illuminate\Container\BoundMethod::callBoundMethod() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
PHP  63. Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
PHP  64. call_user_func_array:{/opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  65. ProcessMaker\Jobs\StartEvent->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  66. Illuminate\Support\Facades\Facade::call() /opt/processmaker/ProcessMaker/Jobs/StartEvent.php:52
PHP  67. Illuminate\Support\Facades\Facade::__callStatic() /opt/processmaker/ProcessMaker/Jobs/StartEvent.php:52
PHP  68. ProcessMaker\Application->call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223
PHP  69. Illuminate\Container\BoundMethod::call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php:564
PHP  70. Illuminate\Container\BoundMethod::callBoundMethod() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
PHP  71. Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
PHP  72. call_user_func_array:{/opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  73. ProcessMaker\Jobs\StartEvent->action() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  74. ProcessMaker\BpmnEngine->createExecutionInstance() /opt/processmaker/ProcessMaker/Jobs/StartEvent.php:73
PHP  75. ProcessMaker\Repositories\DefinitionsRepository->createExecutionInstanceRepository() /opt/nayra/src/ProcessMaker/Nayra/Engine/EngineTrait.php:95
PHP  76. spl_autoload_call() /opt/processmaker/ProcessMaker/Repositories/DefinitionsRepository.php:31
PHP  77. Composer\Autoload\ClassLoader->loadClass() /opt/processmaker/ProcessMaker/Repositories/DefinitionsRepository.php:31
PHP  78. Composer\Autoload\includeFile() /opt/processmaker/vendor/composer/ClassLoader.php:322
PHP  79. include() /opt/processmaker/vendor/composer/ClassLoader.php:444

In ExecutionInstanceRepository.php line 19:
                                                                                                                                                                                                            
  Class ProcessMaker\Repositories\ExecutionInstanceRepository contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ProcessMaker\Nayra\Contracts\Reposito  
  ries\ExecutionInstanceRepositoryInterface::createToken)                                                                                                                                                   
                                                                                                                                                                                                            

PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php:933
Stack trace:
#0 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Foundation\Application-> in /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 933
PHP Stack trace:
PHP   1. {main}() /opt/processmaker/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /opt/processmaker/vendor/phpunit/phpunit/phpunit:53
PHP   3. PHPUnit\TextUI\Command->run() /opt/processmaker/vendor/phpunit/phpunit/src/TextUI/Command.php:155
PHP   4. PHPUnit\TextUI\TestRunner->doRun() /opt/processmaker/vendor/phpunit/phpunit/src/TextUI/Command.php:200
PHP   5. PHPUnit\Framework\TestSuite->run() /opt/processmaker/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:566
PHP   6. PHPUnit\Framework\TestSuite->run() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestSuite.php:765
PHP   7. Tests\Feature\Api\Workflow\WorkflowTest->run() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestSuite.php:765
PHP   8. PHPUnit\Framework\TestResult->run() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestCase.php:798
PHP   9. Tests\Feature\Api\Workflow\WorkflowTest->runBare() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestResult.php:645
PHP  10. Tests\Feature\Api\Workflow\WorkflowTest->runTest() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestCase.php:844
PHP  11. Tests\Feature\Api\Workflow\WorkflowTest->testStartProcessAndCompleteTask() /opt/processmaker/vendor/phpunit/phpunit/src/Framework/TestCase.php:1146
PHP  12. Tests\Feature\Api\Workflow\WorkflowTest->api() /opt/processmaker/tests/Feature/Api/Workflow/WorkflowTest.php:76
PHP  13. Tests\Feature\Api\Workflow\WorkflowTest->json() /opt/processmaker/tests/Feature/Api/ApiTestCase.php:44
PHP  14. Tests\Feature\Api\Workflow\WorkflowTest->call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:317
PHP  15. ProcessMaker\Http\Kernel->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:345
PHP  16. ProcessMaker\Http\Kernel->sendRequestThroughRouter() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
PHP  17. Illuminate\Routing\Pipeline->then() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
PHP  18. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
PHP  19. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  20. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  21. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
PHP  22. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  23. Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  24. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
PHP  25. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  26. Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  27. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
PHP  28. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  29. ProcessMaker\Http\Middleware\TrustProxies->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  30. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/fideloper/proxy/src/TrustProxies.php:57
PHP  31. ProcessMaker\Http\Kernel->Illuminate\Foundation\Http\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
PHP  32. Illuminate\Routing\Router->dispatch() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
PHP  33. Illuminate\Routing\Router->dispatchToRoute() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:597
PHP  34. Illuminate\Routing\Router->runRoute() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:608
PHP  35. Illuminate\Routing\Router->runRouteWithinStack() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:642
PHP  36. Illuminate\Routing\Pipeline->then() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:667
PHP  37. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
PHP  38. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  39. Illuminate\Auth\Middleware\Authenticate->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  40. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
PHP  41. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
PHP  42. Illuminate\Routing\Middleware\SubstituteBindings->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
PHP  43. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
PHP  44. Illuminate\Routing\Router->Illuminate\Routing\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
PHP  45. Illuminate\Routing\Route->run() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Router.php:665
PHP  46. Illuminate\Routing\Route->runController() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
PHP  47. Illuminate\Routing\ControllerDispatcher->dispatch() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
PHP  48. ProcessMaker\Http\Controllers\Api\Workflow\EventController->callAction() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
PHP  49. ProcessMaker\Http\Controllers\Api\Workflow\EventController->callAction() /opt/processmaker/ProcessMaker/Http/Controllers/Controller.php:35
PHP  50. call_user_func_array:{/opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
PHP  51. ProcessMaker\Http\Controllers\Api\Workflow\EventController->triggerStart() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
PHP  52. Illuminate\Support\Facades\Facade::triggerStartEvent() /opt/processmaker/ProcessMaker/Http/Controllers/Api/Workflow/EventController.php:23
PHP  53. Illuminate\Support\Facades\Facade::__callStatic() /opt/processmaker/ProcessMaker/Http/Controllers/Api/Workflow/EventController.php:23
PHP  54. ProcessMaker\Managers\WorkflowManager->triggerStartEvent() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223
PHP  55. ProcessMaker\Jobs\BpmnAction::dispatchNow() /opt/processmaker/ProcessMaker/Managers/WorkflowManager.php:35
PHP  56. Illuminate\Bus\Dispatcher->dispatchNow() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php:26
PHP  57. Illuminate\Pipeline\Pipeline->then() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98
PHP  58. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
PHP  59. Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116
PHP  60. ProcessMaker\Application->call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94
PHP  61. Illuminate\Container\BoundMethod::call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php:564
PHP  62. Illuminate\Container\BoundMethod::callBoundMethod() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
PHP  63. Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
PHP  64. call_user_func_array:{/opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  65. ProcessMaker\Jobs\StartEvent->handle() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  66. Illuminate\Support\Facades\Facade::call() /opt/processmaker/ProcessMaker/Jobs/StartEvent.php:52
PHP  67. Illuminate\Support\Facades\Facade::__callStatic() /opt/processmaker/ProcessMaker/Jobs/StartEvent.php:52
PHP  68. ProcessMaker\Application->call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223
PHP  69. Illuminate\Container\BoundMethod::call() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php:564
PHP  70. Illuminate\Container\BoundMethod::callBoundMethod() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
PHP  71. Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
PHP  72. call_user_func_array:{/opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29}() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  73. ProcessMaker\Jobs\StartEvent->action() /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
PHP  74. ProcessMaker\BpmnEngine->createExecutionInstance() /opt/processmaker/ProcessMaker/Jobs/StartEvent.php:73
PHP  75. ProcessMaker\Repositories\DefinitionsRepository->createExecutionInstanceRepository() /opt/nayra/src/ProcessMaker/Nayra/Engine/EngineTrait.php:95
PHP  76. spl_autoload_call() /opt/processmaker/ProcessMaker/Repositories/DefinitionsRepository.php:31
PHP  77. Composer\Autoload\ClassLoader->loadClass() /opt/processmaker/ProcessMaker/Repositories/DefinitionsRepository.php:31
PHP  78. Composer\Autoload\includeFile() /opt/processmaker/vendor/composer/ClassLoader.php:322
PHP  79. include() /opt/processmaker/vendor/composer/ClassLoader.php:444
``
