### ISSUE TITLE
Remove Unused Migrations

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#549]
Remove Unused Migrations

**Comment by velkymx** [comment]
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/Users/username/dev/bpm/node_modules/webpack/bin/webpack.js:348
			throw err;
			^

Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/fontZoom/fontZoom'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at resolveMonacoPath (/Users/username/dev/bpm/node_modules/monaco-editor-webpack-plugin/index.js:26:18)
    at use.options.pre.featurePaths.map (/Users/username/dev/bpm/node_modules/monaco-editor-webpack-plugin/index.js:113:51)
    at Array.map (<anonymous>)
    at createLoaderRules (/Users/username/dev/bpm/node_modules/monaco-editor-webpack-plugin/index.js:113:31)
    at MonacoWebpackPlugin.apply (/Users/username/dev/bpm/node_modules/monaco-editor-webpack-plugin/index.js:55:19)
    at Compiler.apply (/Users/username/dev/bpm/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/username/dev/bpm/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/Users/username/dev/bpm/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/Users/username/dev/bpm/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/Users/username/dev/bpm/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/username/dev/bpm/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2018-08-25T14_23_34_837Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2018-08-25T14_23_34_867Z-debug.log
